# Site settings
title: Mees Lindeman
email: mees@lindeman.nu
description: >-
  MSc Student in Artificial Intelligence at University of Amsterdam, 
  exploring conceptual questions in AI systems.
baseurl: ""
url: "https://meeslindeman.github.io"
twitter_username: # your_twitter_username
github_username: meeslindeman
linkedin_username: # your_linkedin_username

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Collections
collections:
  publications:
    output: true
    permalink: /:collection/:name/
  research:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "publications"
    values:
      layout: "publication"
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research"